### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by NayanKaran** [NayanKaran/TV_Arena#19]
Choose images, text, icons, fonts.

**Comment by NayanKaran** [comment]
Footer text: `Created by Mandal & Wale © 2022`
Logo: `TV Arena`

**Comment by wale-prog** [comment]
The navigation bar will consist of a movie logo, which will have a link to the homepage, and three other menu namely:
- `Movie`: it will carry the number representing how many movies there are on the page.
- `News`: it is supposed to link the user to movie-related news but will not be implemented in this project.
-  `Most viewed`:  it is supposed to link the user to the top 10 most viewed movies which is also not implemented in this project.
